### ISSUE TITLE
[1-0-1-93][Normal] Characters can get stuck in very thigh spaces.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#251] opened 2021-08-12 18:43 UTC
Explosive Storage again for easy reproduction.
Milla doesn't have problem with getting out, because of the Super Shield Burst, but Carol for example, can get stuck permanently. Pressing right can result in "against the wall" animation.

![Screen2](https://user-images.githubusercontent.com/7067769/129251270-ddff6882-dbbd-42ab-9389-e9a6805cdac9.png)
![Screen3](https://user-images.githubusercontent.com/7067769/129251271-566a10f8-1f32-49d5-aa6b-24902f7dad68.png)

**Comment by whitelilydragon** [comment] 2021-08-17 02:11
This is a duplicate of #241, unfortunately. It's a known thing!

**Closed as completed by whitelilydragon** 2021-08-17 02:11 UTC
Labels: Bug - Class C
