### ISSUE TITLE
[Release 1.0][Minor bug(?)][Feature Suggestion] The Blade Orbiter's blades suddenly stop and disappear; make them fade out/explode/move completely offscreen instead 

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#165] opened 2021-02-19 23:51 UTC
I always thought that looked a little quirky. Just me?

**Comment by whitelilydragon** [comment] 2021-02-20 01:13
I would like to have little touches like that myself, but it would be impractical for the following reasons:

A) This is behavior that matches the original game
B) I can't guarantee that the particle effects would play as intended, so if the player rushes away from the blade orbiter as it leaves the instance activation zone of the camera, it's going to disappear anyway
C) I do not have object pooling systems implemented in the game for things like this, so I can't have extra instances dedicated to playing particle effects when spawned

So, I will have to label this as #Won't Fix, I'm sorry ; ^ ;

**Closed as completed by whitelilydragon** 2021-02-20 01:13 UTC
Labels: Won't Fix
