### ISSUE TITLE
[1-17-6-7-25][Major] Climbing up Ladders causes Shield Crystals to vanish

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#40] opened 2020-09-16 21:11 UTC
Credit goes to Treya for clipping this!
https://clips.twitch.tv/SeductiveSmoggyDugongTooSpicy

When you pick up a shield (underwater or otherwise) and try to go up a ladder, it causes the shield to vanish without effect and it makes a horrible noise.

**Comment by whitelilydragon** [comment] 2020-09-17 05:41
Turns out, it's a regression from a previous fix, where I had interrupted Milla's cube-spawning phase during ladder movement. It wasn't checking specifically enough for Milla's current cube phase, so it'd just- disable cube or item states *entirely* while on ladders!

It should be fixed now, thank for reporting!

**Closed as completed by whitelilydragon** 2020-09-17 05:41 UTC
