### ISSUE TITLE
[1.0.0.24][Minor] You can destroy a target during the loading transition

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#195] opened 2021-02-25 22:51 UTC
https://user-images.githubusercontent.com/69774625/109229795-1c7a3b00-77c4-11eb-9d35-69d3b93c172c.mp4

As seen in the video, you are able to destroy targets in during the loading transition. This may or may not cause an unfair advantage for Lilac in particular, since her cyclone counts as an attack (which is why you are able to destroy a target right away, so long as it is close to the spawn).

**Comment by whitelilydragon** [comment] 2021-02-26 05:33
This is essentially a duplicate of Issue #196, so I am closing this ticket, because I have already created a working solution for #196.

Thank you for reporting!

**Closed as completed by whitelilydragon** 2021-02-26 05:33 UTC
Labels: Duplicate
