### ISSUE TITLE
Loop collission issues

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#1] opened 2020-08-17 00:26 UTC
Weird behaviour regarding Slope tiles

**Comment by Deckardsmegson** [comment] 2020-08-17 00:49
Videolinks on discord

https://discordapp.com/channels/468371770747912192/739994967186997329/744574293001895988
https://discordapp.com/channels/468371770747912192/739994967186997329/744578197781217330
https://discordapp.com/channels/468371770747912192/684817552727080976/744586413265125427

**Comment by Deckardsmegson** [comment] 2020-08-17 01:24
https://cdn.discordapp.com/attachments/744727129123455006/744727483789737984/SPEEEN.mp4
https://cdn.discordapp.com/attachments/744727129123455006/744727484599238666/Millendulum_2.mp4
https://cdn.discordapp.com/attachments/744727129123455006/744727478320496720/Carullllllll.mp4
https://cdn.discordapp.com/attachments/744727129123455006/744727477762654228/Millendulum.mp4
https://cdn.discordapp.com/attachments/744727129123455006/744727472938942604/Craol.mp4

**Comment by whitelilydragon** [comment] 2020-12-18 09:26
I'm closing these because our double-sided slope collision system has changed so much since this post, that any bugs caused by the old system are rendered null at this point. Please open a new ticket for issues regarding any side effects from the refactoring!

**Closed as completed by whitelilydragon** 2020-12-18 09:26 UTC
