### ISSUE TITLE
[1.0.0.18][Minor][Carol] Holding down in a roll while colliding with a wall and holding jump jets her up small walls

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#124] opened 2021-02-19 03:38 UTC
https://user-images.githubusercontent.com/69790793/108454193-c84de480-7220-11eb-81c7-da9147e9b174.mp4

**Comment by whitelilydragon** [comment] 2021-02-19 04:11
First off, I appreciate you testing the game String! Every other issue you have reported is a genuine concern for the release candidate builds, but I have labeled this one as #Won't Fix, and here is why:

In Freedom Planet 1, you have an initial acceleration of 0.667 pixels, when starting your walk cycle, which is what kickstarts forward movement, before traditional acceleration kicks in. (Basically, you can start running up steep slopes as soon as you press a horizontal direction, without sliding backwards like you would in Sonic the Hedgehog.)

And, when you run up against a wall, this initial kick forward is reset, so that when you've cleared the obstacle or wall, you get that initial kick of momentum back, allowing you to clear the obstacle much faster than you would in Sonic the Hedgehog. This is one of many things that makes Freedom Planet unique.

So, on paper, at least, this should be intended behavior.

**Closed as completed by whitelilydragon** 2021-02-19 04:11 UTC
Labels: Won't Fix
