### ISSUE TITLE
[1.0.0.27] Funkiness involving slope in Bouncy Launcher

### ISSUE THREAD

**Issue by Leo40Git** [whitelilydragon/ShangMuArchitect#211] opened 2021-03-02 20:01 UTC
https://user-images.githubusercontent.com/7997354/109707362-bfef9500-7ba2-11eb-8ab8-4005f77e1124.mp4

damn it Carol

**Comment by whitelilydragon** [comment] 2021-03-03 04:28
This is a duplicate of #105, sorry!

**Closed as completed by whitelilydragon** 2021-03-03 04:28 UTC
Labels: Duplicate
