### ISSUE TITLE
(1.0.0.46) The Camera Zoom Out spawners only work once before having to reset the game

### ISSUE THREAD

**Issue by Curonn** [whitelilydragon/ShangMuArchitect#231] opened 2021-03-20 22:00 UTC
The first time I go through the spawner in normal gameplay it works, but then every time after that it does nothing. If I die, restart the stage, or even exit the stage and go back in the spawn ceases to function. I have to restart my game entirely for it to work one more time before repeating the same issue. This happens with both the 25% and the 50% Camera Zoom Out spawners.

**Comment by whitelilydragon** [comment] 2021-03-24 03:51
I would need to see which maps you're creating which this affects, because I can't reproduce this issue on my end. You may be placing them in ways the the game doesn't expect, so there is a lot to rule out here.

**Comment by whitelilydragon** [comment] 2021-04-01 04:53
Double-posting to ask if you can provide the affected map files, or a clean recording of the behavior? It's hard to know whether this is user error or a genuine edge case with the camera zoom gimmick that no one's caught before. I need more information!

If you prefer recordings, you can use OBS to get a direct capture of the game window, or WebMCam if OBS doesn't like your hard drive:

https://github.com/obsproject/obs-studio/releases
https://github.com/michaelmob/WebMCam/releases

**Comment by whitelilydragon** [comment] 2021-08-17 02:30
Closing this ticket because of a lack of additional feedback for this bug. If it is indeed an edge case with a known trigger, someone else may find it and post it as a new bug report.

**Closed as completed by whitelilydragon** 2021-08-17 02:30 UTC
