### ISSUE TITLE
[1.0.0.39][Loop Colissions] Ceiling Loops with flat surface tiles near them can be clipped into

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#216] opened 2021-03-07 01:36 UTC
https://cdn.discordapp.com/attachments/739994967186997329/817931526921650226/2021-03-07_02-26-53.mp4
https://cdn.discordapp.com/attachments/739994967186997329/817931871307563008/2021-03-07_02-24-45.mp4
https://cdn.discordapp.com/attachments/739994967186997329/817932357511675954/2021-03-07_02-30-28.mp4

Every character has the ability to accidentally (or intentionally) clip inside this formation of tiles (Lilac through Dragonboosting, Carol with her bikeboosting and Milla with Super Shield Bursts)

https://user-images.githubusercontent.com/69774625/110226239-d58bf400-7eed-11eb-9c1b-5ca90a8289ca.mp4

**Comment by whitelilydragon** [comment] 2021-03-07 02:35
This is essentially a duplicate of #198, sorry!

**Closed as completed by whitelilydragon** 2021-03-07 02:35 UTC
Labels: Duplicate
